"""Update user model with roles and add child table

Revision ID: d5e8991e4675
Revises: e0caffba4b95
Create Date: 2025-03-08 10:27:51.193183

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd5e8991e4675'
down_revision = 'e0caffba4b95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('calon_ibu_prediction', schema=None) as batch_op:
        batch_op.alter_column('riwayat_gizi',
               existing_type=mysql.ENUM('ya', 'tidak'),
               type_=sa.String(length=10),
               existing_nullable=False)
        batch_op.alter_column('konsumsi_gizi',
               existing_type=mysql.ENUM('sering', 'jarang', 'tidak pernah'),
               type_=sa.String(length=10),
               existing_nullable=False)
        batch_op.alter_column('cek_kesehatan',
               existing_type=mysql.ENUM('ya', 'tidak'),
               type_=sa.String(length=10),
               existing_nullable=False)
        batch_op.alter_column('riwayat_stunting',
               existing_type=mysql.ENUM('ya', 'tidak'),
               type_=sa.String(length=10),
               existing_nullable=False)
        batch_op.alter_column('pendidikan',
               existing_type=mysql.ENUM('tidak sekolah', 'sd', 'smp', 'sma', 'd3', 's1', 's2'),
               type_=sa.String(length=20),
               existing_nullable=False)
        batch_op.alter_column('pola_asuh',
               existing_type=mysql.ENUM('sudah', 'belum'),
               type_=sa.String(length=10),
               existing_nullable=False)
        batch_op.alter_column('ekonomi',
               existing_type=mysql.ENUM('kurang baik', 'cukup baik', 'baik', 'baik sekali'),
               type_=sa.String(length=20),
               existing_nullable=False)
        batch_op.alter_column('hasil_prediksi',
               existing_type=mysql.TEXT(charset='utf8mb4', collation='utf8mb4_0900_ai_ci'),
               type_=sa.String(length=10),
               existing_nullable=False)

    with op.batch_alter_table('stunting_prediction', schema=None) as batch_op:
        batch_op.alter_column('hasil_prediksi',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=50),
               type_=sa.String(length=10),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stunting_prediction', schema=None) as batch_op:
        batch_op.alter_column('hasil_prediksi',
               existing_type=sa.String(length=10),
               type_=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=50),
               existing_nullable=False)

    with op.batch_alter_table('calon_ibu_prediction', schema=None) as batch_op:
        batch_op.alter_column('hasil_prediksi',
               existing_type=sa.String(length=10),
               type_=mysql.TEXT(charset='utf8mb4', collation='utf8mb4_0900_ai_ci'),
               existing_nullable=False)
        batch_op.alter_column('ekonomi',
               existing_type=sa.String(length=20),
               type_=mysql.ENUM('kurang baik', 'cukup baik', 'baik', 'baik sekali'),
               existing_nullable=False)
        batch_op.alter_column('pola_asuh',
               existing_type=sa.String(length=10),
               type_=mysql.ENUM('sudah', 'belum'),
               existing_nullable=False)
        batch_op.alter_column('pendidikan',
               existing_type=sa.String(length=20),
               type_=mysql.ENUM('tidak sekolah', 'sd', 'smp', 'sma', 'd3', 's1', 's2'),
               existing_nullable=False)
        batch_op.alter_column('riwayat_stunting',
               existing_type=sa.String(length=10),
               type_=mysql.ENUM('ya', 'tidak'),
               existing_nullable=False)
        batch_op.alter_column('cek_kesehatan',
               existing_type=sa.String(length=10),
               type_=mysql.ENUM('ya', 'tidak'),
               existing_nullable=False)
        batch_op.alter_column('konsumsi_gizi',
               existing_type=sa.String(length=10),
               type_=mysql.ENUM('sering', 'jarang', 'tidak pernah'),
               existing_nullable=False)
        batch_op.alter_column('riwayat_gizi',
               existing_type=sa.String(length=10),
               type_=mysql.ENUM('ya', 'tidak'),
               existing_nullable=False)

    # ### end Alembic commands ###
